package com.example.gameoflifewallpaper

class NativeEngine {

    init {
        // Load the .so file generated by CMake with our defined name
        System.loadLibrary("gameoflifewallpaper")
    }

    // Signature of 'external' functions that connect to JNI
    external fun initGame(width: Int, height: Int, chunkSize: Int, patternIndex: Int)
    external fun updateGame()
    external fun getGrid(): ByteArray?
    external fun setCell(x: Int, y: Int)
    external fun getWidth(): Int
    external fun getHeight(): Int
}